POST http://127.0.0.1:8080/api/v2/admin/action
Content-Type: application/json

{
  "action": "imageUpdate",
  "data": [
    {
      "name": "1-2",
      "path": "tp",
      "hash": "123214asdasad",
      "type": "map"
    },
    {
      "name": "1-3",
      "path": "tp",
      "hash": "123214asdsasd",
      "type": "map"
    }
  ]
}
