/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionHeader: typeof import('./components/common/ActionHeader.vue')['default']
    CancelConfirmDialog: typeof import('./components/common/CancelConfirmDialog.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElText: typeof import('element-plus/es')['ElText']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    MainAsideMenu: typeof import('./components/MainAsideMenu.vue')['default']
    MainBanner: typeof import('./components/MainBanner.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PluginPreferenceForm: typeof import('./components/plugin/PluginPreferenceForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShadowCard: typeof import('./components/ShadowCard.vue')['default']
    SubPageIndex: typeof import('./components/SubPageIndex.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ToDocument: typeof import('./components/common/ToDocument.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}
