rootProject.name = "arona"
include("arona-core")
include("arona-plugin:test")
include("arona-plugin:arona")
include("arona-plugin:kivotos")
include("arona-plugin:example")
include("arona-plugin:debugger")
include("arona-plugin:custom-menu")
include("arona-plugin:hello-world")
include("arona-plugin:chat-command")
include("arona-plugin:user-recorder")
include("arona-plugin:content-audit")
include("arona-plugin:maintain-notifier")
